# 셀프 어텐션 수행

변수 정의

In [1]:
import torch

In [2]:
x = torch.tensor([
                 [1.0, 0.0, 1.0, 0.0],
                 [0.0, 2.0, 0.0, 3.0],
                 [1.0, 1.0, 2.0, 0.0]
])

w_query = torch.tensor([
                 [1.0, 0.0, 1.0],
                 [1.0, 0.0, 0.0],
                 [0.0, 0.0, 1.0],
                 [0.0, 1.0, 0.0]
])

w_key = torch.tensor([
                 [0.0, 1.0, 1.0],
                 [1.0, 0.0, 0.0],
                 [1.0, 1.0, 0.0],
                 [0.0, 1.0, 0.0]
])

w_value = torch.tensor([
                 [0.0, 2.0, 1.0],
                 [1.0, 3.0, 0.0],
                 [0.0, 0.0, 2.0],
                 [1.0, 0.0, 0.0]
])

쿼리, 키, 값 만들기

In [6]:
querys = torch.matmul(x, w_query)
keys = torch.matmul(x, w_key)
values = torch.matmul(x, w_value)

print("쿼리: \n", querys)
print("키: \n",  keys)
print("값: \n", values)

쿼리: 
 tensor([[1., 0., 2.],
        [2., 3., 0.],
        [2., 0., 3.]])
키: 
 tensor([[1., 2., 1.],
        [2., 3., 0.],
        [3., 3., 1.]])
값: 
 tensor([[0., 2., 3.],
        [5., 6., 0.],
        [1., 5., 5.]])


어텐션 스코어 만들기

In [7]:
attention_score = torch.matmul(querys, keys.T)

print("어텐션 스코어 \n", attention_score)

어텐션 스코어 
 tensor([[ 3.,  2.,  5.],
        [ 8., 13., 15.],
        [ 5.,  4.,  9.]])


소프트맥스 확률값 만들기

In [8]:
import numpy as np
from torch.nn.functional import softmax

In [9]:
key_dim_sqrt = np.sqrt(keys.shape[-1])
attention_probs = softmax(attention_score / key_dim_sqrt, dim=1)

print("softmax 확률값\n", attention_probs)

softmax 확률값
 tensor([[0.2112, 0.1186, 0.6702],
        [0.0132, 0.2365, 0.7503],
        [0.0860, 0.0483, 0.8657]])


가중합하기

In [10]:
weighted_value = torch.matmul(attention_probs, values)

print("가중합\n", weighted_value)

가중합
 tensor([[1.2631, 4.4849, 3.9847],
        [1.9327, 5.1969, 3.7913],
        [1.1071, 4.7903, 4.5867]])
